### ISSUE TITLE
maven导包报错

### ISSUE THREAD

**Issue by jakkkkead** [uhfun/swagger-more#8]
Cannot resolve com.github.uhfun:swagger-more-ui:1.0.2
以及：<sourceDirectory>src/main/java</sourceDirectory>
 报：cannot resolve file java
包都找不到。。

**Comment by hanger-source** [comment]
swagger-more-ui 1.0.2-SNAPSHOT

**Comment by jakkkkead** [comment]
> swagger-more-ui 1.0.2-SNAPSHO

**Comment by jakkkkead** [comment]
> swagger-more-ui 1.0.2-SNAPSHOT

>  <dependency>
            <groupId>com.github.uhfun</groupId>
            <artifactId>swagger-more-ui</artifactId>
            <version>1.0.2-SNAPSHOT</version>
        
没写错啊，就是找不到。。
